from . import start
from . import register_handler
from . import courses_handler
from . import near_location_handler
from . import contact_handler
from . import test
from . import update_db
from . import admin
from . import echo